on:
  schedule:
    - cron:  "0 0 * * *"

jobs:
  run-proaction:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: proactionhq/proaction/action@v0.4.6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}

      - uses: peter-evans/create-pull-request@v2.8.1
        with:
          commit-message: "[proaction] updating workflow"
          title: Updating workflow from Proaction
          token: ${{secrets.PROACTION_TOKEN}}
